# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_library
cc_library(
    name = "utility_lib",
    # srcs = glob(["**/*.cc"]),
    hdrs = ["utility.h"],
    visibility = ["//visibility:public"],
)

