# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lock_unlock_main",
    srcs = ["lock_unlock_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "lock_guard_main",
    srcs = ["lock_guard_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "shared_mutex_main",
    srcs = ["shared_mutex_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)
