cc_test(
    name = "map_reduce_test",
    srcs = ["map_reduce_test.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/main/map_reduce/lib:map_reduce",
        "@googletest//:gtest_main",
    ],
)
