# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "basic_exception",
    srcs = ["basic_exception.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)

cc_binary(
    name = "future_promise_thread",
    srcs = ["future_promise_thread.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)

cc_binary(
    name = "future_promise_jthread",
    srcs = ["future_promise_jthread.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)

cc_binary(
    name = "exception_ptr",
    srcs = ["exception_ptr.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)

cc_binary(
    name = "central_queue",
    srcs = ["central_queue.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)

cc_binary(
    name = "safe_locks",
    srcs = ["safe_locks.cc"],
    copts = [
        "-std=c++23",
    ],
    deps = [
        "//src/lib:logger",
    ],
)
