# https://docs.bazel.build/versions/master/be/c-cpp.html#cc_binary
cc_binary(
    name = "main",
    srcs = ["main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "memory_order_main",
    srcs = ["memory_order_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "memory_order_counter_main",
    srcs = ["memory_order_counter_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "release_acquire_main",
    srcs = ["release_acquire_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)

cc_binary(
    name = "release_acquire_3t_main",
    srcs = ["release_acquire_3t_main.cc"],
    deps = ["//src/lib:SolutionLib"],
)


cc_binary(
    name = "release_acquire_main_simple",
    srcs = ["release_acquire_main_simple.cc"],
    deps = ["//src/lib:SolutionLib"],
)







